; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[ctools][version] = "1.3"

projects[devel][version] = "1.3"

projects[simplehtmldom][version] = "1.12"

projects[views][version] = "3.7"

; Themes
projects[omega][version] = "3.1"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[d7td][download][type] = ""
projects[d7td][download][url] = ""
projects[d7td][type] = "theme"

